services:
  nextjs-app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: nextjs-bun-app-dev
    restart: unless-stopped
    env_file:
      - .env
    environment:
      NODE_ENV: development
      PORT: 3000
      HOSTNAME: 0.0.0.0
      DATABASE_URL: postgresql://admin:mysecretpassword@postgres:5432/mydatabase
    ports:
      - '3000:3000'
    volumes:
      # Mount source code for hot reload
      - ./src:/app/src
      - ./public:/app/public
      - ./prisma:/app/prisma
      - ./prisma.config.ts:/app/prisma.config.ts
      # Exclude node_modules and .next from being overwritten
      - /app/node_modules
      - /app/.next
      - /app/src/generated
    depends_on:
      - postgres
    networks:
      - devops-pipeline

  postgres:
    image: postgres:16-alpine
    container_name: postgres-db-dev
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: mydatabase
    ports:
      - '5433:5432'
    volumes:
      - postgres-data-dev:/var/lib/postgresql/data
    networks:
      - devops-pipeline

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin-dev
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - pga-data-dev:/var/lib/pgadmin
    ports:
      - '5050:80'
    depends_on:
      - postgres
    networks:
      - devops-pipeline

volumes:
  postgres-data-dev:
  pga-data-dev:

networks:
  devops-pipeline:
    driver: bridge
